---
- name: Create config directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ photoprism_data_directory }}/storage"

- name: Install Docker container
  docker_container:
    name: photoprism
    image: photoprism/photoprism
    pull: true
    ports:
      - "{{ photoprism_port }}:2342"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ photoprism_data_directory }}/storage:/photoprism/storage:rw"
      - "{{ photoprism_photos_directory }}:/photoprism/originals:rw"
    env:
      PHOTOPRISM_SITE_CAPTION: "{{ photoprism_site_caption }}"
      PHOTOPRISM_ADMIN_USER: "{{ photoprism_admin_user }}"
      PHOTOPRISM_ADMIN_PASSWORD: "{{ photoprism_admin_password }}"
      PHOTOPRISM_SITE_URL: "https://{{ photoprism_site_prefix }}.{{ ansible_nas_domain }}"
      PHOTOPRISM_DATABASE_DRIVER: "{{ photoprism_database_driver }}"
      PHOTOPRISM_DATABASE_SERVER: "{{ photoprism_database_server }}"
      PHOTOPRISM_DATABASE_NAME: "{{ photoprism_database_name }}"
      PHOTOPRISM_DATABASE_USER: "{{ photoprism_database_user }}"
      PHOTOPRISM_DATABASE_PASSWORD: "{{ photoprism_database_password }}"
    restart_policy: unless-stopped
    memory: 4g
    labels:
      traefik.enable: "{{ photoprism_available_externally  }}"
      traefik.http.routers.gitlab.rule: "Host(`{{ photoprism_site_prefix }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.gitlab.tls.certresolver: "letsencrypt"
      traefik.http.routers.gitlab.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.gitlab.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.gitlab.loadbalancer.server.port: "2342"